name: TimedRanks
main: com.github.CubieX.TimedRanks.TimedRanks
depend: [Vault]
softdepend: [PermissionsEx, zPermissions, bPermissions, PermissionsBukkit]
version: 1.2.0
description: Automated, timed rank promotion and demotion

commands:
    tr:
      description: Using TimedRanks. /vip can be used as alias for /tr!
      aliases: vip
      usage: /tr version | reload | status | promote | demote | add | sub | pause | resume | pay | list | del

permissions:
    
    timedranks.manage:
        description: Allows all player dependend actions (promoting, demoting, ect.)
        default: op

    timedranks.admin:
        description: Allows reloading the plugin and all other commands.
        default: op