name: TimedRanks
main: com.github.CubieX.TimedRanks.TimedRanks
depend: [Vault]
softdepend: [PermissionsEx, zPermissions, bPermissions, PermissionsBukkit]
version: 1.4.1
description: Automated, timed rank promotion and demotion

commands:
    tr:
      description: Using TimedRanks. /vip can be used as alias for /tr!
      aliases: vip
      usage: /tr version | reload | status | promote | demote | add | sub | pause | resume | pay | list | del | help

permissions:
    
    timedranks.manage:
        description: Allows all player dependend actions (promoting, demoting, ect.) which do not mess up things
        default: op

    timedranks.status.own:
        description: Allows listing own promotion status
        default: op

    timedranks.status.other:
        description: Allows listing other players promotion status
        default: op

    timedranks.admin:
        description: Allows reloading the plugin and all other commands.
        default: op